### ISSUE TITLE
Wettbewerbe-Filter im Modul "Teams veralten" nicht alphabetisch sortiert

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league#10]
Im Backend ist im Modul "Team verwalten" der Wettbewerb-Filter nicht alphabetisch sortiert.

![2015-09-03 13_42_56-fv lochgau e v typo3 4 7 20](https://cloud.githubusercontent.com/assets/863722/9657502/edf39842-5241-11e5-87fe-ed5f95314a57.png)

**Comment by digedag** [comment]
Nach dem Update den BE-Cache löschen (bei T3 6.2 im Install-Tool).
