### ISSUE TITLE
player picture button not working

### ISSUE THREAD

**Issue by fgrosswig** [digedag/cfc_league#14]
![player_pic](https://cloud.githubusercontent.com/assets/803345/10156953/3ccd110c-6686-11e5-9202-604475e71ca4.jpg)
I updated to the last release. before i was able to add to each player a Picture. currently the media button does not work - no popup gives me the ability to add a Picture :-(

**Comment by digedag** [comment]
Works for me in T3 6.2. This is standard TCE functionality. Are you able to add pictures to other records like matches or pages?
Are there any javascript errors? Do you use an admin account?

**Comment by fgrosswig** [comment]
updated to recent version - fixed it.
