### ISSUE TITLE
PHP Exception wenn kein Bild in der Teamnotiz hinterlegt ist.

### ISSUE THREAD

**Issue by mario-naether** [digedag/cfc_league#17]
Hi,

ich schreib hier einfach mal den Bugreport in deutsch ;)

Wir habe eine Teamnotiz über die Ligaverwaltung angelegt.
Typ des Werts = Media (id=1)
Notiz-Typ=Headerbild (id=1)
Mediadatei wurde keins hinterlegt.

Danach funktioniert die Rubrik unter "Teams verwalten" > "Team-Notizen" nicht mehr und es gibt einen Absturz mit der Fehlermeldung
```
Fatal error: Call to a member function getOriginalFile() on a non-object in .../www/typo3conf/ext/rn_base/util/class.tx_rnbase_util_TSFAL.php on line 307 
```

```
public static function createThumbnails($references, $sizeArr=FALSE) {
		$ret = array();
		foreach($references As $fileRef ) {
			$thumbnail = FALSE;
			$fileObject = $fileRef->getOriginalFile(); //->$fileRef ist dann false
			...
		}
}
```

Installierte Extension Versionen:
cfc_league 1.0.1
cfc_league_fe 1.0.0
rn_base 0.14.2

PS: Ich hab zwar die aktuelle Version noch nicht in Verwendung, aber mit dieser sollter das Problem auch auftrehten. 
Benötigt ihr einen Pull-Request oder Patch-File?

**Comment by digedag** [comment]
Pull request können gern eingestellt werden. In dem Fall hab ich den Fix aber schon schnell selbst erstellt. :smile:
