### ISSUE TITLE
ice hockey goals

### ISSUE THREAD

**Issue by fgrosswig** [digedag/cfc_league#2]
hi,
is there an option to allow goals in seconds? due the reason Goals pass on icehockey in seconds not in minutes there needs a way to add goals  for the minute and the second.

thx

**Comment by fgrosswig** [comment]
this isnt yet rolled out into the current release? no right? because i dont see the field in the backend - how to add this code manually?

**Comment by digedag** [comment]
It is not available in TER, but it is in current master. The TER version is really old, you should not use it especially for T3 6.2!

**Comment by fgrosswig** [comment]
hi downloaded the master branch and tried to import it into the extensions. the import fails with the following error:

Please check your uploaded extension "cfc_league". The configuration file "ext_emconf.php" seems to be invalid.

how to update the extension ? with git clone? and how to update the tables then?

**Comment by digedag** [comment]
You should definitely use git clone! Rename your existing extension and install the new one with git clone:
```
cd webroot/typo3conf/ext
mv rn_base rn_base_old
git clone https://github.com/digedag/rn_base.git rn_base
```
Repeat this for all extensions of t3sports. Then open the Install-Tool, check database changes and clear caches.

**Comment by fgrosswig** [comment]
I have uploaded the rn_base and all other extensions as suggested.

the install tool provides this error:

```
Detected Fatal Error
Uncaught exception 'BadFunctionCallException' with message 'TYPO3 Fatal Error: Extension key "rn_base" is NOT loaded!' 
in /usr/www/users/scrbij/t362/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php:122 Stack trace: #0 /usr/www/users/scrbij/t362/typo3conf/ext/t3sportstats/ext_localconf.php(4): TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('rn_base') 
#1 /usr/www/users/scrbij/t362/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php(1529): require('/usr/www/users/...') 
#2 /usr/www/users/scrbij/t362/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php(1509): TYPO3\CMS\Core\Utility\ExtensionManagementUtility::loadSingleExtLocalconfFiles() 
#3 /usr/www/users/scrbij/t362/typo3/sysext/core/Classes/Core/Bootstrap.php(647): TYPO3\CMS\Core\Utility\ExtensionManagementUtility::loadExtLocalconf(false) 
#4 /usr/www/users/scrbij/t362/typo3/sysext/core/Classes/Core/Bootstrap.php(334): TYPO3\CMS\Core\Core\Bootstrap->loadAdditionalConfigurationFromExtensions(false) #5 /usr/www/ in /usr/www/users/scrbij/t362/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php on line 122

**Comment by digedag** [comment]
Ich antworte mal in deutsch, das geht schneller. :wink:  
Probleme von t3sportstats mit rn_base sind mir nicht bekannt. Gab es Fehlermeldungen?
Die Sekunde ist derzeit nur im TCA-Formular der MatchNote drin. Man könnte das aber gut über die Sportart verbinden. Muss ich mir anschauen!

**Comment by fgrosswig** [comment]
Naja nur die obere Fehlermeldung und nach dem ich t3sportstat wieder installiert hatte war das backend und frontend weiß. 

Dann habe ich alles wieder gelöscht und alles ohne t3sportstat installiert. Jetzt gehen wenigstens meine Kader wieder :-)

**Comment by digedag** [comment]
Ich hab mal ein Ticket digedag/t3sportstats#2 angelegt. Das werde ich mir kurzfristig anschauen!

**Comment by digedag** [comment]
Ich schließe dieses Ticket, weil die Eingabe von Sekunden ja schon lang möglich ist. Die Funktionalität unter 7.6 hat sich in letzter Zeit ja auch verbessert. Bei weiteren Problemen bitte neue Tickets anlegen.
