### ISSUE TITLE
Bilder werden nicht angezeigt

### ISSUE THREAD

**Issue by cgroughy** [digedag/cfc_league#21]
Ich erhalte bloss weisse, quadratische Felder vor den Mannschaftsbeschreibungen. Ebenso werden die Personenbilder nicht angezeigt.

![unnamed](https://cloud.githubusercontent.com/assets/18000938/13944637/293b14b2-f007-11e5-9056-c7c5046d522a.png)
Sobald ich bei einem Team ein Logo hochlade, verschwindet dieses weisse Quadrat... Für "Fägy Dürnten" und "Fällanden Grizzlys" habe ich ein Bild im Backend hinterlegt...

Was habe ich falsch gemacht?

**Comment by digedag** [comment]
Ich kann das leider nicht reproduzieren. Egal, wie und wo ich die Logos zuordne, sie werden immer angezeigt.
Bist du sicher, daß du das Static Template "T3sports for TYPO3 6.x" eingebunden hast und das es nach dem normalen Template "T3sports" eingebunden ist? 

Geh mal in den TS-Objectbrowser im BE-Modul Web->Templates und prüfe die Einstellungen für **lib.t3sports.teamLogo.big** Den entscheidenden Teil hab ich im Screenshot mal markiert. Steht da bei dir auch die Klasse für das FAL-Rendering?

![ts_object_browser](https://cloud.githubusercontent.com/assets/965877/14060943/b7e43954-f373-11e5-88a1-46d38e9921fb.png)

**Comment by cgroughy** [comment]
Hallo René

Mega! Nun hat es geklappt... Ich habe das Template 6.x VOR dem T3sports
eingebunden. Das war die Lösung!!! Danke vielmals. Nun kann ich mich hinter
die Formatierung setzen...

Wie kann ich das Datum ink. "Anstoss" so formatieren, dass es nicht heisst
"Sam, 07.11.15 Anstoss: 09:00 Uhr", sondern "07.11.15, 09:00"?

Und wie kann ich unser Team in der Tabelle fett hervorheben?

Das sind meine letzten beiden Fragen. Danach bin ich ruhig ;-)

Beste Grüsse

Raphael

Am 26. März 2016 um 16:59 schrieb René Nitzsche <notifications@github.com>:

**Comment by stemeda** [comment]
@cgroughy ich habe das hier für das Datum:
```
lib {
  t3sports {
    match {
      date.default.strftime = %d.%m.%Y %H:%M
    }
    profile {
      birthday.default.strftime =%d.%m.%Y
    }
    team {
      player.birthday.strftime = %d.%m.%Y
      coach.birthday.strftime = %d.%m.%Y
      supporter.birthday.strftime = %d.%m.%Y
    }
    teamSmall {
      player.birthday.strftime = %d.%m.%Y
      coach.birthday.strftime = %d.%m.%Y
      supporter.birthday.strftime = %d.%m.%Y
    }
  }
}
```
Bei der Tabelle kannst du mal gucken, ob das eigene Team nicht eine andere/zusätzliche CSS-Klasse besitzt. Ansonsten schau mal im TypoScript nach `plugin.tx_cfcleaguefe_competition.leaguetable.table.markClub.override` und `plugin.tx_cfcleaguefe_competition.leaguetableAllTime.table.markClub.override`. Hier wird das festgelegt.
