### ISSUE TITLE
PHP Error tx_cfcleague_models_Stadium::getInstance

### ISSUE THREAD

**Issue by stemeda** [digedag/cfc_league#29]
Core: Error handler (BE): PHP Warning: Declaration of tx_cfcleague_models_Stadium::getInstance($uid) should be compatible with tx_rnbase_model_data::getInstance($data = NULL) in .../ext/cfc_league/models/class.tx_cfcleague_models_Stadium.php line 0

**Comment by stemeda** [comment]
@digedag could this be fixed? this is spamming my error log. do you need more information? I'm running PHP 7.0

**Comment by digedag** [comment]
Should be fixed now. Please update cfc_league and cfc_league_fe as well!

**Comment by stemeda** [comment]
thanks!
