### ISSUE TITLE
Support Typo3 CMS 8 LTS 

### ISSUE THREAD

**Issue by supergfg** [digedag/cfc_league#35]
Hi,
hat jemand schon Erfahrungen unter 8.7.x gemacht? Läuft da T3Sports?

Fehlen noch Anpassungen oder sind Anpassungen geplant?

**Comment by digedag** [comment]
Ich kann schon mal sagen, daß T3sports in TYPO3 8.7 nicht funktioniert. Es müssen ein paar Anpassungen an den BE-Modulen gemacht werden. Zeitplan zur Anpassung kann ich leider nicht nennen.

**Comment by digedag** [comment]
Der aktuelle Master läßt sich jetzt in TYPO3 8.7 nutzen. Es scheint soweit auch alles zu funktionieren. Optische Anpassungen kann man aber sicher noch machen. :wink:

**Comment by stemeda** [comment]
Hey,

ich habe meine Installation auf Typo3 geupdated. Es läuft soweit bisher ohne Probleme.

Im Admin-Tool unter "Important Actions" gibt es jetzt einen neuen Abschnitt "TCA Migrations" in dem viele Meldungen wie

```
The 4th parameter 'specConf' of the field 'showitem' with fieldName = 'hidden' has been migrated, from TCA table "tx_cfcleague_club['types']['0']['showitem']"to "tx_cfcleague_club['types']['0']['columnsOverrides']['hidden']['defaultExtras']".
```
angezeigt werden.

**Comment by digedag** [comment]
@stemeda da werde ich bei Gelegenheit mal reinschauen.

Ich hab heute in rn_base für 7.6 und höher das neue BE-Layout für Module aktiviert. Damit sieht auch T3sports nun wieder deutlich schicker aus. Mir ist aber natürlich bewußt, daß da noch viel Luft nach oben ist. :wink: 
Wer es ausprobieren will, muss `rn_base` und `cfc_league` aktualisieren.

**Comment by digedag** [comment]
Die TCA-Meldungen sind bei mir jetzt alle weg! Unbedingt rn_base mit aktualisieren, da von dort eine neue Methode verwendet wird.

**Comment by stemeda** [comment]
@digedag danke, die Meldungen sind weg :-)

**Comment by stemeda** [comment]
Das kann wohl geschlossen werden, oder? Bei mir läuft es seit :-)
