### ISSUE TITLE
Class 'tx_cfcleague_sports_Handball' not found

### ISSUE THREAD

**Issue by stemeda** [digedag/cfc_league#39]
```Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'tx_cfcleague_sports_Handball' not found | Error thrown in file .../typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 4538.```

I checked my extension folder in `cfc_league/sports` is a file with name `class.tx_cfcleague_sports_Handball.php`. Maybe we have a missing include? The error happens when trying to modify a competition.

Using PHP 7.0, Typo3 7.6.21, Current versions of rn_base, cfc_league and cfc_league_fe from GtiHub.

**Comment by digedag** [comment]
Can you provide a complete stacktrace? I cannot reproduce the error with this configuration. Are you running in composer mode? This means you can install new extensions by composer only.

**Comment by stemeda** [comment]
Sorry for late response. I want to reproduce it. The error happens for a week in August. Afterwards it doesn't happen any more.
