### ISSUE TITLE
allow dummy picture of player

### ISSUE THREAD

**Issue by fgrosswig** [digedag/cfc_league#4]
please add some part to allow a dummy pic (via TS) to give a player a dummy picture if the player has no picture set.

**Comment by bastians** [comment]
Gibt es hier für nicht ganz so TS-sichere noch etwas mehr Input? ;)

**Comment by digedag** [comment]
Also nur noch mal zur Erklärung. Das TS-Schnipsel zeigt den Inhalt von **lib.t3sports.dummyLogo**, wenn kein Bild an der Person gefunden wird. Das dummyLogo muss natürlich dann noch konfiguriert werden. Also am besten ein IMAGE-Objekt daraus machen und das gewünschte Dummy-Bild setzen.
