### ISSUE TITLE
Default values in Fexform "Ein neues Spiel anlegen"

### ISSUE THREAD

**Issue by okrgb** [digedag/cfc_league#42]
With the update to TYPO3 7.6.24 and rn_base 1.6.1 versions the input fields for "Spielrunde" and "Spieltag" lost their default values under fexform "Ein neues Spiel anlegen". Previous behavier under TYPO3 6.2.31 and rn_base 1.4.5 was an "prefill" for these fields with the values from where the button "Ein neues Spiel anlegen" was submitted - eg. By submitting the "Ein neues Spiel anlegen" button on "18. Spieltag", the field for "Spielrunde" and "Spieltag" are prefilled with ...[round]" value="18" and ...[round_name]" value="18. Spieltag". Now I get ...[round]" value="0" and ...[round_name]" value="" as default values.

TYPO3 6.2.31 
- cfc_league 1.1.1
- cfc_league_fe 1.1.1
- rn_base 1.4.5
- rn_memento	0.0.1
- t3sportstats 0.4.1	

TYPO3 7.6.24 
- cfc_league  1.1.1 (Git)
- cfc_league_fe 1.1.1
- rn_base 1.6.1
- rn_memento	0.0.1
- t3sportstats 0.4.1	
	 
Is there a possibility to get this nice feature back with TYPO3 7.6.24?

**Comment by digedag** [comment]
Thanks for this report. I haven't notice this bug yet. This also occures for team notes.
Please update rn_base to current repo. To make this fix work.

**Comment by okrgb** [comment]
With the updates for cfc_league 1.1.1 and rn_base 1.6.2 from git this featuere works again.
Thanks for your support!
