### ISSUE TITLE
Falscher Methodenaufruf

### ISSUE THREAD

**Issue by stemeda** [digedag/cfc_league#43]
PHP Runtime Deprecation Notice: Non-static method Tx_Rnbase_Utility_TcaTool::configureWizards() should not be called statically in /typo3conf/ext/cfc_league/Configuration/TCA/tx_cfcleague_club.php line 333

**Comment by digedag** [comment]
Bitte einmal rn_base aktualisieren. Danke für den Hinweis! :-)

**Comment by stemeda** [comment]
Danke, das ging ja fix :+1:
