### ISSUE TITLE
Class 'tx_rnbase' not found in index.php

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league#44]
Ich habe eben auf die neusten Versionen von cfcleague, cfcleage_fe und rn_base aktualisiert, danach kann ich im Backend das T3SPORTS-Modul nicht mehr aufrufen. Die Seite bleibt leer.

Das Error-Log sagt:
`PHP Fatal error:  Class 'tx_rnbase_util_Extensions' not found in [...]/typo3conf/ext/rn_base/class.tx_rnbase.php on line 277`
und 
`PHP Fatal error:  Class 'tx_rnbase' not found in [...]/typo3conf/ext/cfc_league/mod1/index.php on line 48`

TYPO3 6.2.31

**Comment by bastians** [comment]
Also, nach erneutem Öffnen heute morgen, kann ich das Modul wieder aufrufen, war vielleicht doch was mit dem Cache. Aber: Es fehlen die Daten und die Ergebnisse:
![bildschirmfoto 2018-06-13 um 10 09 13](https://user-images.githubusercontent.com/863722/41338291-04bac792-6ef2-11e8-9ece-22605658b82e.png)

> Also am Class-Loading hat sich nichts geändert. Wobei ich auch nicht weiß, wann du zuletzt aktualisiert hast. 
Was meinst du mit zuletzt? Ich war davor auf den folgenden Versionen:
cfc_league: 1.0.2
cfc_league_fe: 1.0.0
rn_base: 1.0.15



> Funktioniert nur das BE nicht oder auch das Frontend?
Das Frontend funtkioniert ohne Probleme.

> Hast du zu den Meldungen auch einen Stacktrace?
Leider nein bzw. wo würde ich den finden? ;)

> Verwendest du den Composer?
Nein.

> Schau mal in der typo3conf/PackageStates.php nach, ob rn_base vor den Extensions von T3sports geladen wird.

Gecheckt, scheint in der richtigen Reihenfolge eingebunden zu sein.

**Comment by digedag** [comment]
Also das war ziemlich alt. Damals wurden die BE-Module noch anders eingebunden. Das erklärt die PHP-Fehler.
Wenn die Formulare jetzt leer bleiben, liegt das vermutlich am Javascript. Öffne mal die JS-Konsole im Browser. Da tauchen bestimmt Fehler auf.
Probier einfach mal den Browser-Cache zu leeren.

**Comment by bastians** [comment]
Danke für den Tipp! Da liegt offenbar der Fehler:
<img width="1481" alt="bildschirmfoto 2018-06-13 um 16 49 57" src="https://user-images.githubusercontent.com/863722/41359051-f0f6d36c-6f29-11e8-847c-06364cbd9c09.png">

Browser-Cache zu leeren scheint nicht zu helfen, aber das sollte ich hinbekommen ;)

Danke nochmals!

**Comment by digedag** [comment]
Soll ich dir was sagen: ich hab den Fehler auch. :man_facepalming: 
Ich weiß auch schon woran es liegt. Bugfix kommt in Kürze!

**Comment by digedag** [comment]
Also nochmal rn_base aktualisieren und die Formulare funktionieren wieder! :smiley:

**Comment by bastians** [comment]
Läuft, besten Dank :)
