### ISSUE TITLE
"Spielplan erstellen" - "Spielrunde: 1000" is not corresponding to the korrekt "Spieltagname"

### ISSUE THREAD

**Issue by okrgb** [digedag/cfc_league#45]
After creating a new "Liga-Wettbewerb" of Typ: Football the "Spielplan" in the backend under "Wettbewerbe verwalten" in "Spieltagsmodus" showed all 182 games under "9. Spieltag". There was no other "Spieltag" to selcet from the pulldown. Detail View of the games showed that all games were created with the Spielrunde: 1000 and not corresponding to the korrekt "Spieltagname" - eg. a game with "Spieltagname" 26. Spieltag was created with Spielrunde: 1000. After changeing the Spielrunde from 1000 to 26 this game was selectable in "Spieltagsmodus" under "26. Spieltag". We had to change all entries for "Spielrunde" to the corresponding "Spieltagname" by hand. 

How is this to prevent?

Number of Teams: 14 
Spielplanschlüssel: 1-2,14-8,13-3,12-4,11-5,10-6,9-7|3-1,2-14,4-13,5-12,6-11,7-10,8-9|1-4,2-3,14-9,13-5,12-6,11-7,10-8|5-1,4-2,3-14,6-13,7-12,8-11,9-10|1-6,2-5,3-4,14-10,13-7,12-8,11-9|7-1,6-2,5-3,4-14,8-13,9-12,10-11|1-8,2-7,3-6,4-5,14-11,13-9,12-10|9-1,8-2,7-3,6-4,5-14,10-13,11-12|1-10,2-9,3-8,4-7,5-6,14-12,13-11|11-1,10-2,9-3,8-4,7-5,6-14,12-13|1-12,2-11,3-10,4-9,5-8,6-7,14-13|13-1,12-2,11-3,10-4,9-5,8-6,14-7|1-14,2-13,3-12,4-11,5-10,6-9,7-8

TYPO3 7.6.28
cfc_league 1.1.1
cfc_league_fe 1.1.1
rn_base 1.6.2
rn_memento 0.0.1
t3sportstats 0.4.1

**Comment by digedag** [comment]
Ich geh mal davon aus, daß die Versionen aus dem TER genutzt wird. Bitte rn_base, cfc_league und cfc_league_fe auf den letzten Stand hier auf Github aktualisieren. Für die 7.6 ist das unbedingt notwendig. Der beschriebene Bug sollte dann auch verschwinden. :smirk:

**Comment by okrgb** [comment]
Besten Dank für die Rückmeldung. Mit dem Update der Erweiterungen rn_base, cfc_league und cfc_league_fe ist der Fehler behoben. Die Erweiterungen sind nun auf dem Stand vom 06.07.2018. Die automatische Vergabe der Spielrunden bei der Spielplan-Erstellung funktioniert wieder. *Daumenhoch*

TYPO3 7.6.28
cfc_league 1.1.1 (Git-Version vom 06.07.2018)
cfc_league_fe 1.1.1 (Git-Version vom 06.07.2018)
rn_base 1.8.2 (Git-Version vom 06.07.2018)
