### ISSUE TITLE
Vorausgewählte Mannschaft beim Hinzufügen von Teamnotizen fliegt raus

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league#46]
Wir nutzen für die Position von Spielern in einer Mannschaft die Teamnotizen. Damit das Anlegen schneller geht, nutze ich beim Speichern die Option "Speichern und neues Objekt anlegen" (das Speichern-Icon mit dem +). 

Ich habe nun das Problem, dass nach dem zweiten Speichern einer Teamnotiz die Mannschaft nicht mehr vorausgewählt ist sondern das DropDown leer ist:
![180819-t3sports-teamnotizen-problem](https://user-images.githubusercontent.com/863722/44306238-ea81f580-a38a-11e8-82dd-ca0fe6bffecd.gif)

Ich muss dann die Ansicht veranlassen und eine neue Teamnotiz anlegen. Dann klappt es wieder ein Mal und dann beim nächsten Eintrag ist die Mannschaft wieder weg.

Passiert unter TYPO3 6.2 und 7.6 mit der neusten Versionen von cfc_league, bin mir aber unsicher, ob das ein cfc_league-Problem ist oder eines meiner TYPO3-Installation.

**Comment by digedag** [comment]
Da kann ich leider nichts machen. TYPO3 entfernt die defVals nach der Neuanlage des Datensatzes. Wenn du [diese Zeile im Code auskommentierst](https://github.com/TYPO3/TYPO3.CMS/blob/d5fdb1295b6a663c1a46c75a7e2e371d3bc610ed/typo3/sysext/backend/Classes/Controller/EditDocumentController.php#L548), dann funktioniert es.

**Comment by bastians** [comment]
Danke für deine Rückmeldung. Das ist ja ärgerlich. Wundere mich nur, wieso es beim ersten Mal speichern klappt, aber beim zweiten Mal dann nicht mehr?

Und das Problem ist mir erst dieses Jahr in der Vorbereitung der neuen Saison aufgefallen, letztes Jahr war das noch nicht so und da waren wir auch schon (oder noch ;) ) auf TYPO3 6.2.

**Comment by digedag** [comment]
Ich schließe das, weil die Ursache für das Problem im TYPO3 Core liegt.
