### ISSUE TITLE
Support Typo3 CMS 9 LTS

### ISSUE THREAD

**Issue by stemeda** [digedag/cfc_league#47]
Hi,
hat jemand schon Erfahrungen unter 9 LTS gemacht? Läuft da T3Sports?

Fehlen noch Anpassungen oder sind Anpassungen geplant?

**Comment by digedag** [comment]
Also hat zwar etwas gedauert, aber ich kann sagen, ohne Anpassungen wird es nicht funktionieren. Die werden aber die nächsten Wochen kommen...

**Comment by digedag** [comment]
Ich mach das Ticket mal zu, weil ein grundsätzlicher Support für TYPO3 9.5 jetzt gegeben ist. Eine entsprechende Version ist auch im TER.
