### ISSUE TITLE
Umlaute-Problem beim Import von Spielplänen aus dem DFBnet

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league#48]
Ich habe aktuell das Problem, dass es die Umlaute in Mannschaftsnamen verhaut, wenn ich einen Spielplan aus dem DFBnet herunterlade und importiere.

Ich habe mal die Encodierung der CSV-Datei auf UTF-8 mit BOM umgestellt, danach ging es.

Kann man beim Upload TYPO3-seitig sicherstellen, dass die CSV-Datei nochmals korrekt encodiert wird?

**Comment by bastians** [comment]
Um es etwas zu spezifizieren: Die CSV-Datei aus dem DFBnet ist wohl UTF-8 codiert, allerdings scheint diese die Umlaute und auch Sonderzeichen nicht korrekt darzustellen. Wenn man auf UTF16-LE konvertiert, sehen die Umlaute und Sonderzeichen korrekt aus und dann klappt auch der Upload.

Ich habe hier im Code gesehen, dass auf UTF-8 konvertiert wird, sofern die Datei eine ISO-6659-1-Kodierung hat: https://github.com/digedag/cfc_league/blob/master/Classes/Dfb/Synchronizer.php#L56

Ist das die korrekte Stelle, die man ggfs. anpassen müsste? :-)

**Comment by digedag** [comment]
Ja, das ist die korrekte Stelle. Die Dateien, die ich damals hatte, waren wohl noch ISO kodiert...

**Comment by bastians** [comment]
Ok, cool. D.h. mein PR ist mergbar? :-)

**Comment by digedag** [comment]
Ich mach das mal zu. PR ist ja gemerged. :-)
