### ISSUE TITLE
SQL QUERY IS NOT VALID<br/><b>Column 'uid_foreign' cannot be null</b><br />

### ISSUE THREAD

**Issue by fgrosswig** [digedag/cfc_league#5]
Beim anlegen neuer Spieler im Backend bekomme ich diese Fehlermeldung :/ 

Wenn ich nur auf Speichern klicke erscheint die Fehlermeldung: 2: SQL error: 'Unknown column 'extid' in 'field list'' (tx_cfcleague_profiles:NEW54baa3365a6ac)

**Comment by digedag** [comment]
Mach mal eine Datenbank-Compare. In T3 6.2 geht es nur noch im INSTALL-Tool. Dir fehlen ein paar Spalten. Ich denke, daran liegt es.

**Comment by fgrosswig** [comment]
Hi,
Db is current steht da. Keine Felder die bei cfc_league benötigt werden oder fehlen.

Im Backend beim anlegen eines neuen Benutzers ganz unten im Formular ist ein Feld ohne Bezeichnung.

Dahinter steht im quellttext die extuid.


Von: René Nitzsche
Gesendet: Montag, 19. Januar 2015 09:03
An: digedag/cfc_league
Antwort an: digedag/cfc_league
Cc: Falk Großwig
Betreff: Re: [cfc_league] SQL QUERY IS NOT VALID<br/><b>Column 'uid_foreign' cannot be null</b><br /> (#5)



Mach mal eine Datenbank-Compare. In T3 6.2 geht es nur noch im INSTALL-Tool. Dir fehlen ein paar Spalten. Ich denke, daran liegt es.

**Comment by digedag** [comment]
Also in der Tabelle tx_cfcleague_profiles gibt es seit [dem letzten Commit](https://github.com/digedag/cfc_league/commit/2ef80972fb3c7408921e805a546bfb8d99a2df82#diff-7a8d17b3a4b2ed4116e3ee2044ca8786) eine neue Spalte extid. Laut Fehlermeldung ist die bei dir nicht vorhanden.
Mit *Benutzer* meinst du vermutlich *Spieler*. Das letzte Feld ohne Label ist genau diese externe ID. Da auch das Label fehlt, hast du ein Problem mit deinem Cache.

**Comment by fgrosswig** [comment]
ok habe die dateien manuell geupdated - cache geleert und db compare vorher durchgeführt. Nun funktioniert es. Danke für den Hinweis.

**Comment by digedag** [comment]
Ja, früher hat da alles mal der Extension-Manager übernommen... :wink:

**Comment by fgrosswig** [comment]
Was tut extID?

**Comment by digedag** [comment]
Sie ist für die Anbindung von Daten-Dienstleistern gedacht. Da gibt es aber leider nichts konkretes, was frei angeboten werden könnte.
