### ISSUE TITLE
Spielplan-Import setzt falsche Zeit

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league#51]
Ich habe eben festgestellt, dass bei allen Spiele die ich für die aktuelle Saison via dem Sync-Feature importiert habe eine falsche Anpfiffzeit haben, und zwar zwei Stunden mehr als in dem CSV steht. Da scheint also irgendetwas mit der Zeitzone falsch zu laufen, mein Server hat aber gem. php.ini `Europe/Berlin` eingestellt.

Problem reproduzierbar oder liegt das an meine Setup?

**Comment by bastians** [comment]
Also in der Datenbank wird die Zeit als UTC gespeichert. Mein Server steht auf UTC+2. D.h. beim Import müssten bei der Zeit 2 Stunden abgezogen werden. Oder?

**Comment by bastians** [comment]
@digedag Kannst du das Problem reproduzieren? Ich bin gerade dabei zum Rückrundenstart die Spielpläne mit den aktuellen Terminen nochmals zu importieren, damit die Daten aktuell sind und die Zeiten sind um 1 Stunde verschoben.

**Comment by digedag** [comment]
Hast du mal eine Zeile aus der CSV? Dann kann ich das mal testen.

**Comment by bastians** [comment]
Ich habe dir mal die ganze CSV angehängt.

**Comment by digedag** [comment]
Ich kann das Problem reproduzieren! Werd ich beheben!

**Comment by digedag** [comment]
Bitte nochmal probieren. Keine Ahnung, warum ich damals den Offset der Zeitzone addiert hatte...

**Comment by bastians** [comment]
Super, vielen Dank. Passt nun :-)
