### ISSUE TITLE
Undefined class constant 'ICON_WARN' Error nach Update

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league#52]
Nach dem Update auf den aktuellsten Stand der Extension aus dem Repository, erhalte ich beim Aufruf des Moduls im Backend folgende Fehlermeldung:
<img width="666" alt="Bildschirmfoto 2019-08-18 um 09 49 16" src="https://user-images.githubusercontent.com/863722/63221721-7b0d3480-c19d-11e9-8cb2-f25199d57c08.png">

SysLog meldet:

> Core: Error handler (BE): PHP Warning: Use of undefined constant ICON_INFO - assumed 'ICON_INFO' (this will throw an Error in a future version of PHP) in /is/htdocs/wp1xxxxxxx_KBL8Q09Y2Z/www/cms/typo3/prod/typo3conf/ext/cfc_league/mod1/class.tx_cfcleague_mod1_profilesearcher.php line 161

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Undefined class constant 'ICON_WARN' | Error thrown in file /is/htdocs/wp1xxxxxxx_KBL8Q09Y2Z/www/cms/typo3/prod/typo3conf/ext/cfc_league/Classes/Controller/Team/ProfileAdd.php in line 140. Requested URL: https://www.fvloechgau.de/typo3/index.php?M=web_CfcLeagueM1&moduleToken=--AnonymizedToken--

cfc_league: v1.3.0
rn_base: v1.9.2
TYPO3-Version: v8.7.27
PHP-Version: v7.2.21-he.0

Caches etc. habe ich alles gelöscht, keine Veränderung.

**Comment by digedag** [comment]
Ich hab jetzt hoffentlich alle fehlenden Konstanten erwischt! :relieved:

**Comment by bastians** [comment]
Danke für die schnelle Reaktion! Hab's die Version aktualisiert, es kommt aber noch einer. Die Stelle sehe ich in deinem Code aber als gefixt. Hmm.

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Undefined class constant 'ICON_INFO' | Error thrown in file /is/htdocs/wp1xxxxxxx_KBL8Q09Y2Z/www/cms/typo3/prod/typo3conf/ext/cfc_league/mod1/class.tx_cfcleague_mod1_profilesearcher.php in line 163.

**Comment by bastians** [comment]
Ich habe nun mal versucht auf die aktuellste `rn_base` Version 1.10.5 zu aktualisieren, nur dann hängt sich meine Seite komplett auf mit folgendem Fehler:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1382276561: The package "cfc_league" depends on "rn_base" which is not present in the system. | UnexpectedValueException thrown in file /is/htdocs/wp1xxxxxxx_KBL8Q09Y2Z/www/cms/typo3/prod/typo3/sysext/core/Classes/Package/DependencyResolver.php in line 73. 

D.h. er findet `rn_base` gar nicht mehr, aber dabei habe ich es eigentlich korrekt hochgeladen. Hmm.

**Comment by digedag** [comment]
Nutzt du den Composer? Falls ja, dann mal das probieren:
```
composer dump-autoload
```
Falls nein, dann das hier:
```
php typo3/cli_dispatch.phpsh extbase extension:dumpclassloadinginformation
```
Und natürlich in jedem Fall den System-Cache im Install-Tool leeren. Aber das hast du vermutlich schon versucht....

**Comment by bastians** [comment]
Ah, danke. Nun klappt es. Nutze zwar nicht den Composer und auch der Command klappte irgendwie nicht, aber im Install-Tool gibt es diese Option ja auch, die hat geklappt.

Und mit der `rn_base` v1.10.4 ist auch der Fehler weg. :-)

**Comment by digedag** [comment]
Sollte sich erledigt haben.
