### ISSUE TITLE
Feld DSGVO

### ISSUE THREAD

**Issue by entaxi57** [digedag/cfc_league#53]
Hallo René,

gibt es eine Möglichkeit den "Default" bei DSGVO auf "Anonymisieren" zu stellen?

z.Z. richte ich die Namen der Spieler erst einmal ein, ohne Mannschaftszugehörigkeit usw. Danach prüfe ich, ob die DSGVO vorhanden ist.

**Comment by digedag** [comment]
Ich würde dich mal auf [diese Seite verweisen](http://labor.99grad.de/typo3-tca-default-werte-per-tsconfig-setzen/). Über die [TCAdefaults](https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/PageTsconfig/TcaDefaults.html) kann man das anpassen.

**Comment by entaxi57** [comment]
Hallo René,
danke für den Hinweis. Habe es mit diesen Eintrag hinbekommen:
`TCAdefaults.tx_cfcleague_profiles.gdpr = 1`
