### ISSUE TITLE
Ausschlussfelder "Aufstellung" und "Aufstellung (statisch)"

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league#6]
In Benutzergruppen gibt es in den Ausschlussfeldern aktuell keine Möglichkeit, den Reiter "Aufstellungen" auszublenden. Es gibt zwar was zu den Aufstellungen, dies betrifft aber den Reiter "Aufstellungen (statisch)". Man sollte aber beide Reiter konfigurieren können.

**Comment by digedag** [comment]
Ich habe in dem Zuge eine ganze Reihe Feldes als "exclude"-Feld definiert. Es kann sein, daß bei bestehenden Redakteursgruppen diese Feld nun nachträglich noch hinzugefügt werden müssen. Den als Standard sind diese Felder ja nun erstmal deaktiviert.

**Comment by bastians** [comment]
Super, danke!
