### ISSUE TITLE
Fehlender Text unter "Ausgewähltes Plug-In"

### ISSUE THREAD

**Issue by entaxi57** [digedag/cfc_league#67]
Hallo René,

mir ist gerade aufgefallen, dass beim "Seiteninhalt" Reiter "Plug-In" unter "Ausgewähltes Plug-In" nur noch das Icon von T3Sports, aber nicht der Text (Ligaverwaltung bzw. Berichte) des Plug-In angezeigt wird.

Typoy 8.7.27
php 7.3
cfc_league 1.5.1
cfc_league_fe 1.5.2
rn_base 1.12.2

**Comment by digedag** [comment]
Danke für den Hinweis! War mir noch gar nicht aufgefallen. Ist jetzt in cfc_league_fe behoben.

**Comment by entaxi57** [comment]
Hallo René,

sieht wieder gut aus.

Danke für die schnelle Korrektur.
