### ISSUE TITLE
Neue Mannschaft / neuer Verein via Element Browser

### ISSUE THREAD

**Issue by bastians** [digedag/cfc_league#7]
Ist es möglich, beim Hinzufügen von Mannschaften zu Wettbewerben innerhalb des TYPO3 Element Browser die Möglichkeit zu schaffen, Mannschaft bzw. Vereine anzulegen? Das wäre enorm zeitsparend, da es oftmals vorkommt, dass einem Wettbewerb Mannschaften hinzugefügt werden müssen, die zunächst noch erstellt werden müssen.

**Comment by bastians** [comment]
Gibt es Chancen, dies zu implementieren? :)

**Comment by digedag** [comment]
Warum machst du das nicht über das BE-Modul? Da lassen sich sogar mehrere Mannschaften mit einem Klick anlegen.
Die Vereine direkt mit anzulegen, ist vermutlich eher eine Fehlerquelle. Dann wird auch mal schnell ein Verein angelegt, der eigentlich schon im System ist. Außerdem lässt sich schwer eine Zielseite für den Verein festlegen.

**Comment by bastians** [comment]
Nun, ich habe pro Altersklasse und Saison Mannschaften angelegt. Diese
Struktur kopiere ich immer jede Saison, so wandern die bereits angelegten
Mannschaften mit.
Wenn ich nun ein Spiel anlege, prüfe ich vorher immer, ob die Mannschaft in
dieser Altersklasse schon angelegt ist. In 80% ist das der Fall. Wenn es
nicht der Fall ist, wird es aufwendiger, daher mein Vorschlag.
Am 28.03.2015 21:23 schrieb "René Nitzsche" <notifications@github.com>:

**Comment by digedag** [comment]
Ich hab jetzt im Wettbewerb den Wizard integriert. So richtig sinnvoll erscheint mir das aber trotzdem nicht. Bei deinem Vorgehen wäre eine Neuerstellung direkt im Spiel-Datensatz vermutlich das beste. Dort ist es aber tatsächlich deutlich aufwendiger. Dafür müsste ein eigenes Wizard-Script geschrieben werden. Denn das Team muss in jedem Fall zuerst an den Wettbewerb gehängt werden. Das ist dann nicht in 10 Minuten gemacht...

**Comment by bastians** [comment]
Oh, vielen Dank. Bin gespannt :)

**Comment by bastians** [comment]
Habe es eben mal installiert. Es bringt mir an dieser Stelle in der Tat nicht so viel mehr. Vielleicht muss ich zu meiner Ordner-Struktur noch etwas sagen. Diese sieht wie folgt aus:
- Herren
-- Herren 1
-- Herren 2
- Frauen
-- Frauen 1
-- Frauen 2
- A-Junioren
-- A1
-- A2
...
Je Altersklasse habe ich also nochmals einen übergeordneten Ordner. Und dort speichere ich die Mannschaften, da es oft vorkommt, dass unsere Teams gegen andere Altersklassen spielen, jedoch innerhalb der übergeordneten Altersklasse. Bspw. spielen unsere A2-Junioren gegen die A1-Junioren eines anderen Vereins.
Daher ging mein Request, das anlegen einer Mannschaft im Element Browser zu integrieren.
![150405-t3sports-backend](https://cloud.githubusercontent.com/assets/863722/6996443/542b70ce-db89-11e4-8684-51fa7d80738e.png)

**Comment by bastians** [comment]
Gibt es denn hier noch die Möglichkeit, das an der von mir skizzierten Stelle einzubauen? Oder geht das einfach nicht im Element-Browser?
