### ISSUE TITLE
Game Selection in Team Note not possible

### ISSUE THREAD

**Issue by iresults-tma** [digedag/cfc_league#70]
The game cannot be selected in team notes. Instead the error message: `Unknown type: select, render type: select` is displayed. See also attached screenshot.

I have not found this field in the TCA configuration. Thank you very much for the fix.

![LFV_li__TYPO3_CMS_9_5_20_](https://user-images.githubusercontent.com/32191097/92402728-554c2800-f130-11ea-8086-8c29eaa5f96d.jpg)

**Comment by digedag** [comment]
Is this some kind of customization? There is no field "game" in team note defined. Check TCA in configuration module. I guess there is some third party extension adding this field.

**Comment by iresults-tma** [comment]
Sorry, that was my mistake. You are right, the field was added by a custom extension.
