### ISSUE TITLE
VAR / VAR Assistent

### ISSUE THREAD

**Issue by iresults-tma** [digedag/cfc_league#74]
Wir setzen die Erweiterung für die Website des Liechtensteiner Fussballverbandes ein. Ab der neuen Nations League Saison ist bei den Spielen jeweils ein VAR (Video Assistant Referee) und ein VAR Assistant im Einsatz. Wäre cool, wenn man diese Daten auch sauber erfasse könnte und die Extension um diese 2 Felder (analog Schiedsrichter / Schiedsrichter Assistent) erweitert würde.

**Comment by digedag** [comment]
Die Umsetzung ist im TER released. Ich hoffe, sie funktioniert, wie erwartet. Ticket wird damit geschlossen.
