### ISSUE TITLE
Cannot add Person

### ISSUE THREAD

**Issue by jiargei** [digedag/cfc_league#75]
I'm trying to create a small web page for our football team and I want to use t3sports for it. It looks very powerful.

Unfortunately, I cannot add Players and it seams that the "season" object is missing. I found the documentation from 0.9.1 but it seems quite older than your current version. The version 1.0.0 has no documentation at all

Is there. Even more, I switched to 1.7.1 because the last update from 1.8.0 to 1.8.1 messed up "Wettberwerbe" functionality!

Kind regards,
Jürgen

**Comment by digedag** [comment]
Hallo Jürgen,

wir können das gerne auch auf deutsch klären. Die alte Doku ist grundsätzlich noch gültig. Der Aufbau der Datenstrukturen hat sich nicht geändert. Du solltest unbedingt die Version 1.8.x verwenden. Ich vermute, du nutzt T3 10.4? Ich hab eben versucht in der Version einen Saison-Datensatz zu erstellen. Das hat funktioniert.

> because the last update from 1.8.0 to 1.8.1 messed up "Wettberwerbe" functionality!
Was meinst du damit?

Grundsätzlich: die Datensätze von T3sports kannst du ausschließlich innerhalb von SysFolder erstellen. Eventuell ist das dein Problem. In der Anleitung sollte auch eine empfohlene Baumstruktur drin sein. Es empfiehlt sich, für jede Saison einen eigenen SysFolder zu erstellen und die zugehörigen Datensätze darin anzulegen. Für saisonübergreifende Daten wie Verein oder Personen sollte man extra SysFolder erstellen.

Falls du trotzdem keine Personen erstellen kannst, dann wäre eine Fehlermeldung hilfreich.

**Comment by jiargei** [comment]
Hallo!
Ok, das mit den SysFolder habe ich nicht ganz verstanden - Typo3 ist recht neu für mich.

Folgendes ist mir aufgefallen:

Wenn ich einen Wettbewerb anlege, diesen Speicher und dann auf Schließen gehe, bekomme ich folgende Meldung:

Oops, an error occurred!
Argument 2 passed to System25\T3sports\Controller\Competition\MatchEdit::getFooter() must be an instance of System25\T3sports\Model\CompetitionRound or null, int given, called in /path/to/cms/public/typo3conf/ext/cfc_league/Classes/Controller/Competition/MatchEdit.php on line 80

Dieses Verhalten ensteht unter der Maske "Wettbewerbe verwalten"

Woran kann das liegen?

LG Jürgen

**Comment by digedag** [comment]
Also das war nun wirklich ein Bug. Ich hab eben einen Fix gepushed. Wenn du über das TER installierst, dann musst du etwas warten, bis die neue Version sichtbar wird.

Alternativ kannst du den Bug umgehen, indem du mit dem Listen-Module ein Spiel für den Wettbewerb anlegst. Danach lädt auch das BE-Modul von T3sports wieder. :slightly_smiling_face:  

SysFolder werden in T3 verwenden, um Daten strukturiert abzulegen. Auf Webseiten legst du Inhaltselemente, wie Texte, Bilder oder Plugins an. Ein Fußballspiel, ein Verein oder Spieler sind aber "reine" Datensätze. Diese werden nicht direkt auf einer Webseite angezeigt, sondern über die Plugins. Dadurch kannst du sie beliebig wiederverwenden. Und da diese Daten also nicht direkt einer Webseite zugeordnet sind, kann man sie der guten Ordnung wegen in SysFolder ablegen. Diese SysFolder kannst du auch komplett außerhalb deiner Webseiten-Struktur erstellen. Leg dir SysFolder für deine News an und eben auch SysFolder für die Daten von T3sports.

**Comment by jiargei** [comment]
Danke für Info! Dadurch hatte ich bei Typo3 eine ordentliche Lernkurve!

**Comment by jiargei** [comment]
@digedag gibt es für cfc_league ein slack oder ähnliches? Oder kann ich hier allgemeine Fragen stellen?

zB. Ist es möglich, Spieler auf Basis von Frontend-Benutzern aufzubauen bzw. diese zu übernehmen? der FE-User enthält ja bereits einige der von CFC_LEAGUE benötigten Felder!
