### ISSUE TITLE
TYPO3 V11

### ISSUE THREAD

**Issue by iresults-tma** [digedag/cfc_league#76]
Is it intended to update the extension for TYPO3 11?

**Comment by digedag** [comment]
Ist geplant. Wird aber vermutlich frühestens zum Jahresende hin.

**Comment by stemeda** [comment]
Hey gibt es hier schon etwas neues? Typo3 10 läuft nur unter PHP 7.X, welches keine Updates mehr erhält. Deswegen würde ich gerne Updaten :-) Und Typo3 10 läuft auch im April aus...

@digedag Danke für deine Arbeit!

**Comment by digedag** [comment]
Ja, sieht gut aus. In den nächsten 14 Tagen sollte was kommen.

**Comment by digedag** [comment]
Installation im Backend funktioniert jetzt schon. Allerdings per Composer, weil noch ein spezieller Branch von rn_base benötigt wird.

**Comment by digedag** [comment]
Installation in der 11.5 funktioniert, aber noch nicht unter PHP 8. Hier muss die zentrale Klasse für die Spiele umbenannt werden, weil "match" ab PHP 8 ein reserviertes Schlüsselwort ist. Ist aber in Arbeit.

**Comment by digedag** [comment]
Die Backend-Extension ist jetzt voll unter TYPO3 11.5 und PHP 8 einsetzbar. Leider muss ich die Model-Klasse für die die Spiele umbenennen, da `Match` jetzt ein reserviertes Schlüsselwort ist und nicht mehr verwendet werden darf. Die Klasse heißt nun `Fixture`. Es müssen nun aber auch alle Extensions angepasst werden, die auf diese Klasse zugreifen.

Für cfc_league ist die Umstellung aber abgeschlossen.
