### ISSUE TITLE
backend rights to the t3sports module for non-admin editor - error 503

### ISSUE THREAD

**Issue by HorstBaumann** [digedag/cfc_league#94]
typo3 12.4.7 (composer)
cfc_league 1.11.4
cfc_league_fe 1.11.1

I want to create a regular backend editor (not an admin), who is able to manage games/leagues not just by the list view module,
but also with the t3sport module, an error occurs:
503
Oops, an error occurred!
You don't have access to this module.

![grafik](https://github.com/digedag/cfc_league/assets/11771888/1efc277b-2244-4162-a2ae-35f3108253c5)

in older versions this error never happens (i am using cfc_league since TYPO3 6 - but this is a whole fresh installation)
did i miss a setting or is it a typo3 v12 specific bug ?

**Comment by digedag** [comment]
I will have a look at it.

**Comment by digedag** [comment]
Issue should be fixed with latest commit. You can now configure access to sub modules as well.
Do you need a version tag?

Thanks for notice!

**Comment by HorstBaumann** [comment]
Thanks a lot René !
yes please - "require digedag/cfc-league:1.11.x-dev" does not work ....

**Comment by digedag** [comment]
Tagged with version 1.11.5
:slightly_smiling_face:
